### ISSUE TITLE
Afacad upgrade

### ISSUE THREAD

**Issue by emmamarichal** [Dicotype/Afacad#4]
Hi @ktkm,

For Afacad upgrade, we have to possibilities:
- We can try to add the backslant on what we already have: The upright and italic version. This could be tricky, since we already have the italic.
- In the case it doesn't work ((this is highly likely), we will have to create a new family on GF. I'll need you give me a new name. It can be something like "Afacad Super" or "Afacad Premium", I don't know.
We can let it in that repo, because we a source will be updated, we will need to update the two families... I'll try to write a clear process for this.

I'll let you know if I manage to export the current fonts with the backslant added,
cheers!

**Comment by ktkm** [comment]
You’re right. A new family on GF seems more plausible.

**Comment by ktkm** [comment]
Oh, and I have some small updates for the Black Masters—mostly kerning. Should I wait until you have the exports under control?

**Comment by emmamarichal** [comment]
Yes feel free to add the modifications directly in your repo. I'm making some tests locally! thanks :)

**Comment by emmamarichal** [comment]
Hi @ktkm,

After discussions and tests, we decided to onboard a new family, with a slant axis. 
We will need to find a new name. Can you give me 2 or 3 proposition (or maybe only one if you know exactly how you want to call it :) ). I'll discuss this with my colleagues tomorrow. 

Thanks!

**Comment by ktkm** [comment]
Hello @emmamarichal ,

Just to clarify, would the new family have the full spectrum from “back-slant” to “plain” to “Slant”?

In that case, I can think of two short naming schemes in my order of interest:
1. Afacad Flux (historical/scientific) -- “Flux”, or the flow of liquids, and relates to historical cartography, where rivers were marked with the back-slanted type. 
2. Afacad Slant (function/axis name) -- “Slant” is perhaps more descriptive of what to expect.

Cheers!

**Comment by emmamarichal** [comment]
> Just to clarify, would the new family have the full spectrum from “back-slant” to “plain” to “Slant”?
Yes, it will look like something like this: 

https://github.com/Dicotype/Afacad/assets/64773544/ded0f328-6b0d-4870-bf68-87a6d9968238


Excellent, thank you, I'll submit these names to my colleagues and I'll let you know :)

**Comment by ktkm** [comment]
Nice! What software is doing the interpolation in your demo?

**Comment by emmamarichal** [comment]
https://fontgauntlet.com/ :)

**Comment by emmamarichal** [comment]
Hi @ktkm, we chose "Afacad Flux". I'll review the files and export the font. I'll send you a PR soon!

**Comment by ktkm** [comment]
Ah, good news! Thank you @emmamarichal !

**Comment by ktkm** [comment]
Hello @emmamarichal , hope you’re well. Any news regarding the review?

**Comment by emmamarichal** [comment]
Hi @ktkm! I started to work on it, but I have some other projects that are coming before. I'll let you know :)
